num_train_steps: 1100000
action_std_schedule: 'linear(1.0,0.1,100000)'
action_noise_clip: 0.3

seed: 123
memory_size: 5000

lr: 1e-3
batch_size: ${memory_size}


update_every_steps: ${memory_size}
num_updates: 2

eval_every_steps: ${memory_size}
num_eval_episodes: 3



discount: 0.95

num_seed_steps: ${memory_size}

render_im_width: 256
render_im_height: 256


exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}

hydra:
  run:
    dir: ./exp/${exp_group}/${exp_id}
